title: TonkeyTong

description: >
  Ich Dokumentiere hier meinen Weg fürs lernen von Azure und erstelle dabei einfache Erklärungen der einzelnen Themen für mich selbst aber auch andere welche beim 
  Vorbereiten auf Azure Zertifikate helfen sollen aber auch einfach zum nachschlagen gedacht sind.  

lang: de-DE
timezone: Europe/Berlin

theme: minima

header_pages:
  - ueber.md
